name = "Researcher"
license = "GPL-3.0"
licenselink = "https://github.com/cdohara/dark-hugo-researcher/blob/master/LICENSE"
description = "A dark variant of the Researcher theme for Hugo."
tags = ["blog", "bootstrap", "clean", "minimal", "personal", "responsive", "resume", "simple"]
features = ["bootstrap", "responsive", "simple"]
homepage = "https://github.com/cdohara/dark-hugo-researcher"
min_version = "0.74.3"

[author]
  name = "Enya Yang"
  homepage = "https://enya.bam.moe"

[original]
  author = "Ankit Sultana"
  homepage = "https://github.com/ankitsultana"
  repo = "https://github.com/ankitsultana/researcher"
